---
name: Check Markdown Links
on:
  push:
    branches:
      - main
    paths:
      - '**.markdown'
  pull_request:
    paths:
      - '**.markdown'

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: -v "docs/**/*.markdown"
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
